[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.github
  | \.idea
  | venv
  | database_scripts
)/
'''

# flake8 does not and will not integrate with pyproject.toml, reference .flake8 for configuration

[tool.isort]
profile = "black"
line_length = 120
